### ISSUE TITLE
Not found Chrome Driver issue

### ISSUE THREAD

**Issue by Jerrysmd** [sueszli/notionSnapshot#13]
Hi Sueszli,

I got the issue about no Chrome Driver found for 119.0.6045 Version

I have tired in Github CodeSpace, Ubuntu and local windows machine. All faced the Driver issue

Error msg:

`ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/119.0.6045/chromedriver_win32.zip`
`ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/119.0.6045/chromedriver_linux64.zip`

![image](https://github.com/sueszli/notionSnapshot/assets/25995001/0d8aed99-c3e7-4560-8554-f51aeaeb6e46)

**Comment by dansteingart** [comment]
same error on bionic. thanks.

**Comment by sueszli** [comment]
see: https://github.com/sueszli/notionSnapshot/blob/master/docs/progress.md#choosing-a-scraping-library

see: https://github.com/sueszli/notionSnapshot/issues/7

this is because the resource position changed.

selenium sucks and `webdriver_manager` isn't up to date anymore.

the next meaningful step would be a complete rewrite in playwright.

I won't have time to do this  myself right now but I'll gladly review pull requests.

**Comment by sceboucher** [comment]
I was able to solve this by just doing `pip update webdriver_manager` - it may not be a full fix but seems to have worked in my case.

**Comment by sueszli** [comment]
@sceboucher oh nice!

yeah it feels weird building a project on top of another one that's even jankier (webdrive_manager).

instead of a full replacement of selenium, using docker could be a simple alternative.

**Comment by Jerrysmd** [comment]
Thanks @sceboucher @sueszli 

I fix this issue by using `pip install --upgrade webdriver_manager` in Linux environment

**Comment by sueszli** [comment]
Nice! Thanks @Jerrysmd
